// Generates supabase/seed.sql: 48 teams (12 groups) + 104 matches (72 group + 32 knockout).
// Reproducible — re-run with `npm run seed:gen`. Kickoff times are reasonable placeholders
// spread across the real tournament window (Jun 11 – Jul 19, 2026); verify/adjust in the
// admin UI as real fixtures are confirmed.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = fileURLToPath(new URL("../supabase/seed.sql", import.meta.url));

// iso2 -> flag emoji (special-cased for the home nations)
function flag(iso2, special) {
  if (special === "scotland") return "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}";
  if (special === "england") return "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}";
  return [...iso2.toUpperCase()].map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65)).join("");
}

// [name, FIFA code, iso2, special]
const GROUPS = {
  A: [["Mexico", "MEX", "MX"], ["South Africa", "RSA", "ZA"], ["South Korea", "KOR", "KR"], ["Czechia", "CZE", "CZ"]],
  B: [["Canada", "CAN", "CA"], ["Switzerland", "SUI", "CH"], ["Qatar", "QAT", "QA"], ["Bosnia & Herzegovina", "BIH", "BA"]],
  C: [["Brazil", "BRA", "BR"], ["Morocco", "MAR", "MA"], ["Scotland", "SCO", "", "scotland"], ["Haiti", "HAI", "HT"]],
  D: [["United States", "USA", "US"], ["Paraguay", "PAR", "PY"], ["Australia", "AUS", "AU"], ["Türkiye", "TUR", "TR"]],
  E: [["Germany", "GER", "DE"], ["Curaçao", "CUW", "CW"], ["Costa Rica", "CRC", "CR"], ["Ecuador", "ECU", "EC"]],
  F: [["Netherlands", "NED", "NL"], ["Japan", "JPN", "JP"], ["Tunisia", "TUN", "TN"], ["Sweden", "SWE", "SE"]],
  G: [["Belgium", "BEL", "BE"], ["Egypt", "EGY", "EG"], ["Iran", "IRN", "IR"], ["New Zealand", "NZL", "NZ"]],
  H: [["Spain", "ESP", "ES"], ["Chile", "CHI", "CL"], ["Saudi Arabia", "KSA", "SA"], ["Uruguay", "URU", "UY"]],
  I: [["France", "FRA", "FR"], ["Senegal", "SEN", "SN"], ["Norway", "NOR", "NO"], ["Iraq", "IRQ", "IQ"]],
  J: [["Argentina", "ARG", "AR"], ["Algeria", "ALG", "DZ"], ["Austria", "AUT", "AT"], ["Jordan", "JOR", "JO"]],
  K: [["Portugal", "POR", "PT"], ["Colombia", "COL", "CO"], ["Uzbekistan", "UZB", "UZ"], ["DR Congo", "COD", "CD"]],
  L: [["England", "ENG", "", "england"], ["Croatia", "CRO", "HR"], ["Ghana", "GHA", "GH"], ["Panama", "PAN", "PA"]],
};

// Assign team ids 1..48 in group order.
const teams = [];
let tid = 1;
const groupTeamIds = {};
for (const [g, members] of Object.entries(GROUPS)) {
  groupTeamIds[g] = [];
  for (const [name, code, iso2, special] of members) {
    teams.push({ id: tid, name, code, group: g, flag: flag(iso2, special) });
    groupTeamIds[g].push(tid);
    tid++;
  }
}

const esc = (s) => s.replace(/'/g, "''");
function iso(date) {
  return date.toISOString().replace(".000Z", "Z");
}

// ---- Group matches: round-robin (6 per group), spread across kickoff slots ----
const RR = [
  [0, 1], [2, 3], // round 1
  [0, 2], [3, 1], // round 2
  [3, 0], [1, 2], // round 3
];
const matches = [];
let mid = 1;
const base = Date.UTC(2026, 5, 11, 16, 0, 0); // Jun 11 2026 16:00 UTC
let slot = 0;
// interleave so each round's matches are grouped chronologically
for (let round = 0; round < 3; round++) {
  for (const g of Object.keys(GROUPS)) {
    const pairings = [RR[round * 2], RR[round * 2 + 1]];
    for (const [hi, ai] of pairings) {
      const day = Math.floor(slot / 5);
      const hourSlot = [15, 18, 21, 24, 27][slot % 5];
      const kickoff = new Date(base + day * 864e5 + (hourSlot - 16) * 36e5);
      matches.push({
        id: mid++,
        stage: "group",
        group: g,
        label: `Group ${g} — MD${round + 1}`,
        home: groupTeamIds[g][hi],
        away: groupTeamIds[g][ai],
        kickoff: iso(kickoff),
      });
      slot++;
    }
  }
}

// ---- Knockout placeholders ----
function ko(stage, count, startUTC, hoursStep, prefix) {
  for (let i = 0; i < count; i++) {
    const kickoff = new Date(startUTC + i * hoursStep * 36e5);
    matches.push({
      id: mid++,
      stage,
      group: null,
      label: `${prefix} ${i + 1}`,
      home: null,
      away: null,
      home_ph: `${prefix} ${i + 1} — Home (TBD)`,
      away_ph: `${prefix} ${i + 1} — Away (TBD)`,
      kickoff: iso(kickoff),
    });
  }
}
ko("r32", 16, Date.UTC(2026, 5, 28, 18, 0), 12, "Round of 32");
ko("r16", 8, Date.UTC(2026, 6, 4, 18, 0), 24, "Round of 16");
ko("qf", 4, Date.UTC(2026, 6, 9, 18, 0), 24, "Quarter-final");
ko("sf", 2, Date.UTC(2026, 6, 14, 22, 0), 24, "Semi-final");
ko("third", 1, Date.UTC(2026, 6, 18, 19, 0), 24, "Third-place play-off");
ko("final", 1, Date.UTC(2026, 6, 19, 19, 0), 24, "Final");

// ---- Emit SQL ----
let sql = "-- AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.\n";
sql += "-- 48 teams, 104 matches. Idempotent (upsert).\n\n";

sql += "insert into public.teams (id, name, code, group_label, flag_emoji) values\n";
sql += teams
  .map((t) => `  (${t.id}, '${esc(t.name)}', '${t.code}', '${t.group}', '${t.flag}')`)
  .join(",\n");
sql += "\non conflict (id) do update set name=excluded.name, code=excluded.code, group_label=excluded.group_label, flag_emoji=excluded.flag_emoji;\n\n";

sql += "insert into public.matches (id, stage, group_label, label, home_team_id, away_team_id, home_placeholder, away_placeholder, kickoff_at) values\n";
sql += matches
  .map((m) => {
    const grp = m.group ? `'${m.group}'` : "null";
    const home = m.home ?? "null";
    const away = m.away ?? "null";
    const hph = m.home_ph ? `'${esc(m.home_ph)}'` : "null";
    const aph = m.away_ph ? `'${esc(m.away_ph)}'` : "null";
    return `  (${m.id}, '${m.stage}', ${grp}, '${esc(m.label)}', ${home}, ${away}, ${hph}, ${aph}, '${m.kickoff}')`;
  })
  .join(",\n");
sql += "\non conflict (id) do update set stage=excluded.stage, group_label=excluded.group_label, label=excluded.label, home_team_id=excluded.home_team_id, away_team_id=excluded.away_team_id, home_placeholder=excluded.home_placeholder, away_placeholder=excluded.away_placeholder, kickoff_at=excluded.kickoff_at;\n";

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, sql);
console.log(`Wrote ${OUT}: ${teams.length} teams, ${matches.length} matches.`);
